services:
  hatchling:
    image: hatchling
    build:
      context: ..
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
      dockerfile: ./docker/Dockerfile
    volumes:
      - ${HATCH_HOST_CACHE_DIR}:/home/appuser/.hatch
      - ${HATCH_LOCAL_PACKAGE_DIR}:/app/.local
    user: "${USER_ID}:${GROUP_ID}"
    env_file: .env
    environment:
      - PYTHONPATH=/app
    network_mode: ${NETWORK_MODE}
    tty: true
    stdin_open: true

  hatchling_dev:
    image: hatchling_dev
    build:
      context: ..
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
      dockerfile: ./docker/Dockerfile
    volumes:
      - ${HATCH_HOST_CACHE_DIR}:/home/appuser/.hatch
      - ${HATCH_LOCAL_PACKAGE_DIR}:/app/.local
      - ../:/app # Mount source code for development overriding copied /app in docker file
    user: "${USER_ID}:${GROUP_ID}"
    env_file: .env
    network_mode: ${NETWORK_MODE}
    tty: true
    stdin_open: true
    
